name: "Astro Project Check"

on:
    push:
        branches: [ "main" ]
    pull_request:

jobs:
    lint:
        name: "Prettier Check"
        runs-on: ubuntu-latest
       
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            
            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                node-version: latest
                cache: 'npm'
            - name: Install packages
              run: npm ci
            - name: Run Prettier checks
              run: npx prettier --check .

    astro-check:
        name: "Astro Check"
        runs-on: ubuntu-latest
       
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            
            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                node-version: latest
                cache: 'npm'
            - name: Install packages
              run: npm ci
            - name: Run Astro checks
              run: npx astro check

    build:
        name: "Build Check"
        runs-on: ubuntu-latest
       
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
            
            - name: Setup Node
              uses: actions/setup-node@v7
              with:
                node-version: latest
                cache: 'npm'
            - name: Install packages
              run: npm ci
            - name: Run Build
              run: npx run build
                